do:
  space:
    key: ${SPACE_KEY}
    secret: ${SPACE_SECRET}
    endpoint: ${SPACE_ENDPOINT}
    region: ${SPACE_REGION}
    bucket: ${SPACE_BUCKET}

cors:
  endpoint: ${CROSS_ORIGIN_ENDPOINT}

server:
  address: "0.0.0.0"

eif-api:
  jwt:
    secret: '357538782F4125442A472D4B6150645367566B59703373367639792442264528'
    token-prefix: 'Bearer'
    token-header: 'Authorization'
    token-expiration: 86400
    token-issuer: 'EIF APP TFF'

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          explicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    change-log: classpath:database/master-changelog.yaml
    default-schema: public
    enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB