do:
  space:
    key: ${SPACE_KEY}
    secret: ${SPACE_SECRET}
    endpoint: ${SPACE_ENDPOINT}
    region: ${SPACE_REGION}
    bucket: ${SPACE_BUCKET}

server:
  address: "0.0.0.0"

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
